apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: e2e
  name: e2e
spec:
  containers:
  - name: e2e
    image: registry.k8s.io/e2e-test-images/agnhost:2.40
    resources: {}
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
