apiVersion: apps/v1
kind: Deployment
metadata:
  name: mayapp-deploy
  labels:
    env: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      env: demo
  template:
    metadata:
      labels:
        env: demo
        name: myapp
    spec:
      containers:
      - image: nginx:1.23.4-alpine
        name: myapp
        ports:
        - containerPort: 80
