apiVersion: v1
kind: Service
metadata:
  name: myapp-cluster
  labels:
    env: demo
spec:
  type: ClusterIP
  selector:
    env: demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  