apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
  labels:
    env: demo
spec:
  type: NodePort
  selector:
    env: demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001