apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    env: demo
    tier: backend
spec:
  replicas: 5
  selector:
    matchLabels:
      env: demo
  template:
    metadata:
      labels:
        env: demo
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.4