apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    env: demo
spec:
  replicas: 4
  selector:
    matchLabels:
      env: demo
  template:
    metadata:
      labels:
        env: demo
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
