apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: demo
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo 40daysofkubernetes
          restartPolicy: OnFailure